const {
  NODE_ENV,
  BCAR_ANSAN_CROSS_LOGIN_URL,
  BCAR_ANSAN_CROSS_CAR_REGISTER_URL,
  DYNAMO_DB_REGION,
  BCAR_TABLE,
  BCAR_INDEX,
  BCAR_CATEGORY_TABLE,
  BCAR_CATEGORY_INDEX,
  REGION,
  JOB_DEFINITION_NAME,
  PRIVATE_REGISTRY_BASE_URL,
  PRIVATE_REGISTRY_PATH,
  TAG_NAME,
  TASK_EXECUTION_ROLE_ARN,
  GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY,
  GOOGLE_ACCOUNT_SHEET_NAME,
  GOOGLE_SPREAD_SHEET_ID,
  GOOGLE_KCRURL_SHEET_NAME,
} = process.env

const envs = {
  NODE_ENV: NODE_ENV || "local",
  BCAR_ANSAN_CROSS_LOGIN_URL: BCAR_ANSAN_CROSS_LOGIN_URL!,
  BCAR_ANSAN_CROSS_CAR_REGISTER_URL: BCAR_ANSAN_CROSS_CAR_REGISTER_URL!,
  DYNAMO_DB_REGION: DYNAMO_DB_REGION!,
  BCAR_TABLE: BCAR_TABLE!,
  BCAR_INDEX: BCAR_INDEX!,
  BCAR_CATEGORY_TABLE: BCAR_CATEGORY_TABLE!,
  BCAR_CATEGORY_INDEX: BCAR_CATEGORY_INDEX!,
  GOOGLE_CLIENT_EMAIL: GOOGLE_CLIENT_EMAIL!,
  GOOGLE_PRIVATE_KEY: GOOGLE_PRIVATE_KEY!.replaceAll("\\n", "\n"),
  GOOGLE_ACCOUNT_SHEET_NAME: GOOGLE_ACCOUNT_SHEET_NAME!,
  GOOGLE_KCRURL_SHEET_NAME: GOOGLE_KCRURL_SHEET_NAME!,
  GOOGLE_SPREAD_SHEET_ID: GOOGLE_SPREAD_SHEET_ID!,
}

const deployEnvs = {
  REGION: REGION!,
  JOB_DEFINITION_NAME: JOB_DEFINITION_NAME!,
  PRIVATE_REGISTRY_BASE_URL: PRIVATE_REGISTRY_BASE_URL!,
  PRIVATE_REGISTRY_PATH: PRIVATE_REGISTRY_PATH!,
  TAG_NAME: TAG_NAME!,
  TASK_EXECUTION_ROLE_ARN: TASK_EXECUTION_ROLE_ARN!,
}

if (envs.NODE_ENV === 'prod') {
  console.info(process.env);
}

// 여기서 false
if (!Object.values(envs).every(env => env !== undefined)) {
  throw new Error('Importing required env failed')
}

export { envs, deployEnvs }
